name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install uv
        run: pip install "uv>=0.1"

      - name: Cache uv wheels
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install project and dev dependencies
        run: |
          uv pip install --system -e .[dev]

      - name: Lint with Ruff
        run: ruff check --output-format github .

      - name: Check formatting with Black
        run: black --check .

      - name: Static type check with mypy
        run: mypy src tests

      - name: Run unit tests
        run: pytest -q --cov=src --cov-report=xml

      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

